# Generated by Django 4.1.1 on 2022-09-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.PositiveIntegerField(verbose_name='enrollemnt no')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('year', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth')], max_length=1, verbose_name='year')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.PositiveIntegerField(verbose_name='start time')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('maximum_score', models.PositiveIntegerField(verbose_name='maximum score')),
                ('checker', models.ManyToManyField(to='pursuit_app.img_member')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=255, verbose_name='round name')),
                ('round_type', models.CharField(choices=[('T', 'Test'), ('I', 'Interview'), ('P', 'Project')], default='I', max_length=1, verbose_name='round type')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveIntegerField(verbose_name='season year')),
                ('season_name', models.CharField(max_length=255, verbose_name='season name')),
                ('season_type', models.CharField(choices=[('D', 'Developer'), ('d', 'Designer')], default='D', max_length=1, verbose_name='season type')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollment_no', models.PositiveIntegerField(primary_key='true', serialize=False, verbose_name='enrollment no')),
                ('student_name', models.CharField(max_length=255, verbose_name='student name')),
                ('department', models.CharField(max_length=5, verbose_name='department')),
                ('cg', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='cg')),
                ('role', models.CharField(choices=[('D', 'Developer'), ('d', 'Designer')], default='D', max_length=1, verbose_name='role')),
                ('mobile_number', models.CharField(max_length=14, verbose_name='mobile number')),
                ('email', models.EmailField(max_length=254)),
                ('selection_status', models.CharField(choices=[('D', 'disqualified'), ('S', 'selected'), ('P', 'pending')], default='P', max_length=1, verbose_name='selection status')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pursuit_app.season')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pursuit_app.round')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255, verbose_name='section name')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pursuit_app.round')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='score')),
                ('remark', models.TextField(verbose_name='remark')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pursuit_app.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pursuit_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pursuit_app.season'),
        ),
        migrations.AddField(
            model_name='question',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pursuit_app.section'),
        ),
        migrations.CreateModel(
            name='Interview_Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(verbose_name='remarks')),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='pursuit_app.interview')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pursuit_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='Interview_Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('img_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pursuit_app.img_member')),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panel', to='pursuit_app.interview')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='rounds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pursuit_app.round'),
        ),
        migrations.AddField(
            model_name='interview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='pursuit_app.student'),
        ),
    ]
