# Generated by Django 4.1.1 on 2022-09-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0002_alter_img_member_options_alter_img_member_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img_member',
            options={},
        ),
        migrations.AlterModelManagers(
            name='img_member',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='img_member',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='img_member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='img_member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='img_member',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='img_member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='img_member',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='img_member',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='img_member',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='img_member',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='img_member',
            name='username',
        ),
        migrations.AlterField(
            model_name='img_member',
            name='password',
            field=models.CharField(max_length=1, null=True, verbose_name='password'),
        ),
    ]
