# Generated by Django 4.1.1 on 2022-10-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0004_alter_img_member_enrollment_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='checker',
        ),
    ]
