# Generated by Django 4.1.1 on 2022-10-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0006_img_member_groups_img_member_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_member',
            name='password',
            field=models.CharField(max_length=10, null=True, verbose_name='password'),
        ),
    ]
