# Generated by Django 4.1.1 on 2022-11-01 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0008_question_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='pursuit_app.season'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(max_length=14, null=True, verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pursuit_app.round'),
        ),
    ]
