# Generated by Django 4.1.1 on 2022-11-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0010_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img_member',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='img_member',
            name='user_permissions',
        ),
    ]
