# Generated by Django 4.1.1 on 2022-11-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0014_img_member_groups_img_member_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img_member',
            name='username',
        ),
        migrations.AlterField(
            model_name='img_member',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
