# Generated by Django 4.1.1 on 2022-11-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0015_remove_img_member_username_alter_img_member_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview_remarks',
            name='sections',
        ),
    ]
