# Generated by Django 4.1.1 on 2022-11-27 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0016_remove_interview_remarks_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='pursuit_app.interview')),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
