# Generated by Django 4.1.1 on 2022-11-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0017_interview_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_section',
            name='section_name',
            field=models.CharField(max_length=255, verbose_name='section name'),
        ),
    ]
