# Generated by Django 4.1.1 on 2022-11-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0018_alter_interview_section_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_remarks',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='pursuit_app.section'),
        ),
    ]
