# Generated by Django 4.1.1 on 2022-11-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0019_interview_remarks_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_marks',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='pursuit_app.interview_section'),
        ),
        migrations.AlterField(
            model_name='interview_remarks',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='pursuit_app.interview_section'),
        ),
    ]
