# Generated by Django 4.1.1 on 2022-11-27 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0020_alter_interview_marks_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_marks',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='pursuit_app.section'),
        ),
        migrations.AlterField(
            model_name='interview_remarks',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='pursuit_app.section'),
        ),
        migrations.DeleteModel(
            name='Interview_Section',
        ),
    ]
