# Generated by Django 4.1.1 on 2022-11-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0021_alter_interview_marks_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='start_time',
            field=models.DateTimeField(verbose_name='start_time'),
        ),
    ]
