# Generated by Django 4.1.1 on 2022-11-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0023_alter_interview_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='start_time',
            field=models.PositiveIntegerField(verbose_name='start time'),
        ),
    ]
