# Generated by Django 4.1.1 on 2022-12-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pursuit_app', '0027_alter_interview_panel_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='pursuit_app.question'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='pursuit_app.student'),
        ),
        migrations.AlterField(
            model_name='section',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pursuit_app.round'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='pursuit_app.round'),
        ),
    ]
